name: Telegram Bot

on:
  workflow_dispatch:
    inputs:
      canal:
        description: 'Canal para enviar mensaje'
        required: true
      mensaje:
        description: 'Mensaje para enviar'
        required: true
      # Eliminamos token de inputs

jobs:
  ejecutar-python:
    runs-on: ubuntu-latest
    env:
      MENSAJE: ${{ github.event.inputs.mensaje }}
      CANAL: ${{ github.event.inputs.canal }}
      TOKEN: ${{ secrets.TOKEN }}  # TOKEN guardado en Secrets del repo

    steps:
      - uses: actions/checkout@v4

      - name: Aplicar máscara para valores sensibles
        run: |
          echo "::add-mask::$TOKEN" > /dev/null

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar script de Python
        run: python telegram_bot.py
        env:
          MENSAJE: $MENSAJE
          CANAL: $CANAL
          TOKEN: $TOKEN
